// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiHCSwmVXJbmwMmueSPLUvgfN9TZd5Fs',
    appId: '1:973772251267:web:8534fa543566e35a19fbb6',
    messagingSenderId: '973772251267',
    projectId: 'quizlesson5',
    authDomain: 'quizlesson5.firebaseapp.com',
    storageBucket: 'quizlesson5.appspot.com',
    measurementId: 'G-F3JN0MJE7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKB91c2yRUrR1cB160yFWS3D-4LQeIjfA',
    appId: '1:973772251267:android:5a061f4cc0855c3c19fbb6',
    messagingSenderId: '973772251267',
    projectId: 'quizlesson5',
    storageBucket: 'quizlesson5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowPzDrI9eC3JQAqwL0aQj_-4tUlM7r2s',
    appId: '1:973772251267:ios:26ffaf0b1bd1919e19fbb6',
    messagingSenderId: '973772251267',
    projectId: 'quizlesson5',
    storageBucket: 'quizlesson5.appspot.com',
    iosBundleId: 'com.example.month4Lesson5QuizFirebase',
  );
}
